spring:
  application:
    name: login-microservice
  datasource:
    url: jdbc:mysql://localhost:3306/loginDB
    username: loginUser
    password: Login123.
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: "UnaClaveSuperSecretaLargaParaFirmarTokensJWT123456789012345678901234567890"
